jaffle_shop: # this needs to match the profile in your dbt_project.yml file
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /home/derekwong/data_engineer_zoomcamp/week1/1_terraform_gcp/secret-node-376314-528d41ae156b.json # replace this with the full path to your keyfile
      project: secret-node-376314 # Replace this with your project id
      dataset: dbt_jaffle # Replace this with dbt_your_name, e.g. dbt_bilbo
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
pg-dbt-workshop:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: root
      pass: root
      dbname: docker_prod
      schema: dbt_victoria_mola
    prod:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: prod_root
      pass: prod_pass
      dbname: docker_prod
      schema: master
    
